### ISSUE TITLE
SnappyData jdbc query

### ISSUE THREAD

**Issue by JasonDung** [SnappyDataInc/snappydata#1402]
jdbc:snappydata:pool://ip:1527/route-query=false
use select * from table offset 10 rows fetch next 10 rows only.  
This syntax row table can be supported. but column table do not。
How do I use pagination?

**Comment by sumwale** [comment]
@JasonDung Spark does not support OFFSET primarily because it is quite expensive in a distributed engine (https://issues.apache.org/jira/browse/SPARK-3998). Besides the problem is that if your underlying table data is changing then repeated OFFSET/LIMIT may miss rows or include rows multiple times. That said we do have an issue tracking OFFSET in ComputeDB which should be added by 1.2 release: https://jira.snappydata.io/browse/SNAP-1515

One efficient way could be if your required page size is about the same size as underlying buckets. That is with default 128 buckets you can get 128 pages by adding a filter "spark_partition_id() = ..." to your query.

Perhaps the most generic way right now would be to have an ID column in your data (need not be sequentially increasing). For instance: create table table1WithID using column as monotonically_increasing_id() ID, * from table1. Now run a separate query to see what ranges would be appropriate as per page size (each bucket will have IDs in certain range) and add those range filters to your query. This will avoid the problem of duplicate/missing rows that changing data in table can cause with OFFSET+LIMIT. Using monotonically_increasing_id() becomes a bit problematic if you are appending data to the table from multiple places. In that case you will need to ensure only one appender, fix the max of ID in current data and add that to monotonically_increasing_id(). Even if there are a few duplicates due to concurrent inserts it will not harm pagination much.

Another hackish option is to write the output of query to CSV files in shared location, then use custom code to scan the files and show output with pagination. That is: create table querytmpout_123 using csv options (path '/shared/location') as select ...

All this is assuming your result is large enough that it cannot be stored locally in-memory on client. Otherwise you can materialize the entire result on client and use simple code to page through.

**Comment by JasonDung** [comment]
@sumwale Thank you very much
