### ISSUE TITLE
Best way to connect outside of java/jvm (jdbc vs odbc) ?

### ISSUE THREAD

**Issue by ddorian** [SnappyDataInc/snappydata#485]
Which is ~best/fastest way ? (i'm using python)

Also, regarding odbc, the driver file can't be downloaded from this guide: http://gemfirexd.docs.pivotal.io/docs-gemfirexd/developers_guide/topics/odbc/install_config_odbc.html#concept_d35_lng_rl__section_usg_vrg_fr 

driver link: https://network.pivotal.io/products/gemfirexd

Thank You

**Comment by sumwale** [comment]
@ddorian ODBC driver with SnappyData is based off the new thrift API and packaging is in works. We will be releasing a version in a week or so which will be available from the snappydata github releases page (will inform when it is released).

**Comment by sumwale** [comment]
@ddorian Another option is to directly use the thrift API (perhaps preferred for python instead of going through ODBC translation layer). Its not documented much right now since we have not come to its full scale testing yet but it is fairly stable. You can find a basic readme [here](https://github.com/SnappyDataInc/snappydata/blob/master/cluster/README-thrift.md), the IDL [here](https://github.com/SnappyDataInc/snappy-store/blob/snappy/master/gemfirexd/shared/src/main/java/io/snappydata/thrift/common/snappydata.thrift) and a basic test [here](https://github.com/SnappyDataInc/snappydata/blob/master/cluster/src/test/java/io/snappydata/app/TestThrift.java).

**Comment by sumwale** [comment]
The ODBC drivers for Windows platform is now available from the releases page. So we have the following ways to connect externally (apart from smart connector mode of Spark): a) JDBC, b) ODBC, c) [thrift](https://github.com/SnappyDataInc/snappydata/blob/master/cluster/README-thrift.md) [API](https://github.com/SnappyDataInc/snappy-store/blob/snappy/master/gemfirexd/shared/src/main/java/io/snappydata/thrift/common/snappydata.thrift) (test location is now [here](https://github.com/SnappyDataInc/snappy-store/blob/snappy/master/gemfirexd/tools/src/test/java/io/snappydata/app/TestThrift.java)).

Closing this issue @ddorian
