### ISSUE TITLE
Snappy0.7 Dashborad improvment

### ISSUE THREAD

**Issue by hzxjtx** [SnappyDataInc/snappydata#523]
hi, 
   Snappy 0.7 release version, the dashboard exist some questions:
1. members cannot be sorted
2. why exist so many dead 

![1](https://cloud.githubusercontent.com/assets/6895821/23599324/4fd005a6-027b-11e7-9a8a-45d18f21a28c.jpg)

**Comment by sumwale** [comment]
With SnappyData 0.8, issue 2 mentioned here should have been fixed. The problem was due to connector mode joinees (e.g. via spark-shell, zeppelin) showing up as dead once they leave. This has further been addressed in current master where connector mode no longer joins in as a server rather using thin JDBC connection.

Issue 1 mentioned above is being tracked in JIRA here: https://jira.snappydata.io/browse/SNAP-1337 so closing @hzxjtx
