### ISSUE TITLE
create  snappydata  column table  like hive table  support partition  

### ISSUE THREAD

**Issue by erjunzhang** [SnappyDataInc/snappydata#539]
now  i  want to create  column table  with partition but snappydata partiiton_by not like hive table   partition ,if i want to create column table partiton like  hive table partiton ,how to do , i  want to  query snappydata table   less amount of data

**Comment by piercelamb** [comment]
@erjunzhang Not sure if this helps, but this example shows column table creation with the use of PARTITION_BY using both Spark and pure SQL. http://snappydatainc.github.io/snappydata/howto/#how-to-create-column-tables-and-run-queries

**Comment by sumwale** [comment]
@erjunzhang Can you tell what you find missing in partition_by compared to hive partitions? You can specify both partitioning columns using PARTITION_BY and number of partitions using BUCKETS. Unlike hive tables you can also collocate tables and use way more efficient collocated joins rather than shuffle: https://snappydatainc.github.io/snappydata/howto/#howto-collacatedJoin

Column tables are always partitioned into 113 partitions (even if no partition_by has been specified) which will be generated UUID partitioning by default.

**Comment by erjunzhang** [comment]
@sumwale  snappydata partition_by  is different  hive partition  . snappydata partition_by is like distribution key  but  hive partition is not .    actually  i want to delete or truncate snappydata clolumn table  something data , i konw snappydata table have timestamp

**Comment by sumwale** [comment]
@erjunzhang What's the use-case for deleting an entire partition? Update/delete support is coming soon in SnappyData (https://jira.snappydata.io/browse/SNAP-1387) which will allow precise deletions like on date/time ranges, or even single row.

**Comment by erjunzhang** [comment]
@sumwale  when  someday  data is wrong  , Need to delete the data ,Then insert the new data

**Comment by sumwale** [comment]
@erjunzhang Ok, that should be handled efficiently by delete support in column tables. It will allow all other cases of deletions not just on partitioning columns. Expect for cases of highly concurrent small deletions, the performance should also be good.

**Comment by obaidcuet** [comment]
@sumwale Partitioning (like Hive/Oracle tables), there are two aspects:

- Maintenance: Considering a large table having 500GB data daily. And retention of data on this table is 365 days.
If we schedule purging daily then we need to delete 500GB data daily. If monthly then 15TB data monthly with a single delete operation. And normally we may end up with couple of tables like this.
So, I am not sure how efficient(in terms of time and impact on other operations) delete operation would be in this case.
This problem can easily be solved by adding daily range partition(not snappydata partition, as per my understanding, snappydata partition mostly for distribution purpose) based on any date column, just drop the specific partition like dropping a table, very quick.

- Performance:  Moreover, queries based on the partition key column, will restrict on required partitions rather than a full table scan. This will boos performance as well without having costly index. Lets say for daily aggregations, anyway we will scan all the records for the day and daily range partition could be used for that.

So, in terms of Maintenance & Performance, I see hive/oracle like partition is an integral part of any OLAP/DWH like platform.
Proposing to add this feature(Hive/oracle like partition), it will hugely boost the acceptability of snappydata.

Refs:
https://stackoverflow.com/questions/19128940/what-is-the-difference-between-partitioning-and-bucketing-a-table-in-hive
https://stackoverflow.com/questions/22220837/how-to-add-partition-using-hive-by-a-specific-date

**Comment by sumwale** [comment]
@obaidcuet Thanks a lot for your detailed comments.

Yes we are aware of the difference between partitioning and bucketing, and its rationale in hive design/terminology. However from SnappyData perspective here is where our thinking is currently:

- SnappyData organizes data into partitions but, also within partitions portions of consecutive data are split into column batches for easy handling in memory/disk (24M size [by default](https://github.com/SnappyDataInc/snappydata/blob/master/core/src/main/scala/io/snappydata/Literals.scala#L207)). This means that date/timestamp ranges are automatically handled by these batches assuming the data/timestamp column mostly follows wall clock time so that each column batch will automatically have a small date/time range.

- We have MIN/MAX optimization which tracks the MIN/MAX of all orderable columns in each column batch which is then used to quickly skip/include column batches. This allows any date/time based queries/updates/deletes to be very efficient already by skipping through column batches in each partition as they are scanned, and deletes can drop the whole batch if all of it qualifies. Apart from date/time, usually it allows for efficient filtering for many other column types when the values are grouped together in ingestion (which is quite common).

So the most common case of date/time based queries/updates/deletes is already highly optimized and handled without any additional work on users' part (whether any partitioning is specified or not). It may not be as efficient as dropping a whole partition but it is still sub-second for tens of billions of rows per node.

On the other hand, this approach brings advantages for users:

- Users don't have to think in terms of partitioning for efficient deletes/updates etc. They can just concentrate on partitioning for best join/filter columns to get highly efficient [collocated joins](https://snappydatainc.github.io/snappydata/howto/#how-to-perform-a-collocated-join) and/or filters. While in some cases the deletes/updates and joins may be for the same columns but in most cases they are not so in our experience (e.g. deletes on time date/time ranges vs joins usually on other dimensions).
- One less concept for users to think about especially during design.

To make the above work efficiently for other cases where values may not be grouped together in ingestion, users can provide multi-column partitioning where possible. We have also been looking at expanding partitioning to allow RANGE partitioning and general expression based partitioning [like in row store](http://rowstore.docs.snappydata.io/docs/developers_guide/topics/create-partition-tables/PartitioningTablesExplained.html). We have also been thinking about explicit sub-partitioning so that query engine can do better partition pruning.

**Comment by sumwale** [comment]
@obaidcuet

Adding further to above: we would in fact recommend **against** using DATE/TIMESTAMP as partitioning if those follow wall clock time.

It may be efficient for queries in the hive world to prune heavy aggregation queries to just a single partition but in the world of highly efficient distributed memory cache like SnappyData it is not efficient. If only a single partition is hot and largely being used by queries especially concurrent queries, then that represents a significant bottleneck where only a single partition (e.g. for the current day) is active all the time while others are idle. This serializes execution into a single thread handling that partition (and would be a problem even in Hive).

We recommend using some other relevant dimension for partitioning so that all partitions are active and the query can be executed in a parallel way. The column batch organization means that each partition will skip batches with very little work and move on to the relevant batches quickly, so processing is both distributed and with minimal wasted work. This has been proven to be order of magnitude faster in our testing e.g. with [TAQ](http://www.nyxdata.com/Data-Products/Daily-TAQ) [benchmark](https://github.com/SnappyDataInc/snappydata/blob/master/cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/TAQTest.scala).

**Comment by obaidcuet** [comment]
@sumwale 

Thanks for your nice explanations. Here I am sharing some of my thoughts:

> We have MIN/MAX optimization which tracks the MIN/MAX of all orderable columns

_1. Does it mean integer and double columns will also have Min/Max tracking ( I would like to call it zoning :) ) ?_ 

 > This allows any date/time based queries/updates/deletes to be very efficient already by skipping through column batches in each partition as they are scanned, and deletes can drop the whole batch if all of it qualifies. 

_2. Does delete operation like these requires any extra action (like reorganization or de-fragmentation ) to free up actual disk space ?_

> We recommend using some other relevant dimension for partitioning so that all partitions are active and the query can be executed in a parallel way. 

_3. Each partition of hive is presented as a HDFS directory. Partitions data in hive are actually files under each partition and will be distributed over data nodes naturally based on HDFS blocks size. So, even though one partition (lets say latest day) becomes hot, still it will be processed in parallel. And dropping a partition is just like dropping a HDFS/unix directory._

So, I still think maintaining hive like partition will be a valuable feature in snappydata. 
For the time being , on my above questions, if answer of **question#1** is **yes** and answer of **question#2** is **no**, they will be workaround for hive like partitions.

**Comment by sumwale** [comment]
@obaidcuet 

> 1. Does it mean integer and double columns will also have Min/Max tracking ( I would like to call it zoning :) ) ?

Yes, all numeric (boolean/byte/short/int/long/float/double), decimal and String types.

> 2. Does delete operation like these requires any extra action (like reorganization or de-fragmentation ) to free up actual disk space ?

No user action is required. The SnappyData Oplog files will automatically get dropped (if all batches in the file are gone which will be the case for most of the files in time range delete) or compacted (if only some batches in the file are gone) after a while by the Oplog compactor which is on by default.

> 3. Each partition of hive is presented as a HDFS directory. Partitions data in hive are actually files under each partition and will be distributed over data nodes naturally based on HDFS blocks size.

Are you sure that Spark will create separate partition for each of the files? Don't think that is the case because that will be too many partitions and haven't seen those many even when querying 100GB of data. Will need to check HadoopRDD implementation in Spark. Perhaps that is configurable?

> So, even though one partition (lets say latest day) becomes hot, still it will be processed in parallel.

Even assuming "yes" for the previous question, the distribution is unlikely to be spread out for recent data. For example if the last hour is the hottest one then it is likely to be in a few files and therein will be the bottleneck which will be much more pronounced for concurrent queries. Likewise current day files may be few and the scalability will be restricted by the number of hot files.

The design in SnappData is superior and avoids these bottlenecks since scalability will depend on the distribution of partitioning column and not on time interval. Even for streaming ingest, if looking for only last few minutes of data, the processing will be parallel as much as possible on the dimension that has been specified for partitioning. As in everything, there can be some exceptions like partitioning column has less spread than even time interval, but that choice has to be made based on other considerations like optimizing collocated join query performance, so overall it should have much better performance for the frequent queries.

Btw about performance for TAQ, KDB's site publishes some numbers: http://kparc.com/q4/q4.txt http://kparc.com/q4/readme.txt . While we cannot publish comparative numbers due to its license, suffice to say that SnappyData's numbers are quite favorable to it or better especially when no indexes are involved (indexes on column tables are a high priority item being tracked). Against others there is hardly any comparison like KDB's site also publishes. You can check for yourself with the [code](https://github.com/SnappyDataInc/snappydata/blob/master/cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/TAQTest.scala) that uses synthetic random data. What is interesting there in present context is comparing the case of query on single day data among 16 days of total data vs only single day data.

**Comment by obaidcuet** [comment]
@sumwale Thanks for your time. Seems like I have got my answer.

I am rephrasing our discussion as summary below:

1. There MIN/MAX optimization which tracks the MIN/MAX of all orderable columns (all numeric, date/time, decimal and String types). This allows queries/updates/deletes on these columns to be very efficient by skipping through column batches in each partition as they are scanned, and deletes can drop the whole batch if all of it qualifies.

2. No user action is required to free up actual disk space. The Snappydata Oplog files will automatically get dropped (if all batches in the file are gone which will be the case for most of the files in time range delete) or compacted (if only some batches in the file are gone) after a while by the Oplog compactor which is on by default.

3. We normally use hive/oracle like partition for two purposes i) Maintenance of data purging and ii) Performance gained by partition pruning. Snappydata compliments these with points 1 & 2 above. 

4. Snappydata partition is mainly for distribution and co-located joins. So, unlike hive/oracle partition keys, snappydata partition key should not be date/time, it should be a column that has more unique values (tables with same partition keys, joining them will result co-located join and reduce data movements).

Kindly correct my statements above if anything wrong.

**Comment by sumwale** [comment]
@obaidcuet Sounds perfect. A simple collocated join example using customer ID for partitioning and join is [here](https://snappydatainc.github.io/snappydata/howto/#how-to-perform-a-collocated-join). Update and delete on column tables is a [WIP](https://jira.snappydata.io/browse/SNAP-1389) and will be available in 1.0 (will be in master soon)

> One question though, how the redistribution of snappydata partition table happens while adding or removing a node(Data Server) ?

The total number of partitions is fixed for a table by the BUCKETS option which defaults to 113 (but should be kept larger for larger amount of data like 100s or GBs or TBs) that also determines the number of Spark RDD partitions that are created for scan. Unit of data movement is a bucket, and buckets of collocated tables move together. When a new server joins, then it can specify "-rebalance" option on the startup command-line that will trigger bucket rebalancing and new server will become the primary for some of the buckets (and secondary for some if REDUNDANCY>0 has been specified). There is also a system procedure "call sys.rebalance_all_buckets()" that can be used to trigger a rebalance.

**Comment by obaidcuet** [comment]
@sumwale Thanks. I have no more open question on this topic.

**Comment by sumwale** [comment]
@erjunzhang 
Based on detailed discussions above, at this point the existing support for column tables (and planned ones) should be enough to cover the use-cases. If new use-cases are seen that cannot be covered then will consider extending the partitioning/execution schemes appropriately. Closing this issue for now.
