### ISSUE TITLE
column table support off-heap feature?

### ISSUE THREAD

**Issue by fubo** [SnappyDataInc/snappydata#540]
From our test,We find that sometime analytic applications will be affected by one of the data server because of it's gc. We find the Rowstore document recommend to use off-heap to bypass the gc issues,but this feature only support row table in version 0.8.We wondering that   will we support column table for off-heap feature in future release,otherwise,if we can handle out this problem in other way? thanks!

**Comment by hbhanawat** [comment]
SnappyData column table does not support the offheap storage as of now. But, since Snappy uses Spark's execution engine, you can specify offheap memory for the temporary data blocks that are created during analytical query. 

The two settings that you would need to set are spark.memory.offHeap.enabled and spark.memory.offHeap.size. You can set them in the conf/leads file like this

conf/leads
myleadHost -spark.memory.offHeap.enabled=true -spark.memory.offHeap.size=xxx .....rest of the settings.... 

For the documentation of these properties, checkout the following doc: 

http://spark.apache.org/docs/latest/configuration.html#memory-management

**Comment by sumwale** [comment]
Support for off-heap for column tables is being tracked in https://jira.snappydata.io/browse/SNAP-1454

**Comment by sumwale** [comment]
Closing this since off-heap for column tables was part of 0.9 release.
