### ISSUE TITLE
how to install snappy on Existing spark cluster?

### ISSUE THREAD

**Issue by anubhavj880** [SnappyDataInc/snappydata#680]
I have a production Spark standalone cluster , i do not want to install snappy by download the zip which already has spark inside it. I want to integrate snappy with my existing spark cluster .So  Is it possible ,if it is the please tell me the steps.

**Comment by kneeraj** [comment]
@anubhavj880 please check this.

https://snappydatainc.github.io/snappydata/quickstart/#getting-started-with-your-spark-distribution

and the smart connector mode here:

https://snappydatainc.github.io/snappydata/deployment/#connectormode

**Comment by sumwale** [comment]
@anubhavj880 closing this issue since it is documented as in links above. Note, however, that the query performance of connector mode will usually be quite a bit less than that of embedded mode. The best performance in connector mode will be obtained by having the SnappyData cluster on the same nodes as the Spark cluster so that data fetch can be local.

If there is any trouble in using the mode then please open a new issue.
