### ISSUE TITLE
SnappyData0.9 out of memory

### ISSUE THREAD

**Issue by diwenjing** [SnappyDataInc/snappydata#734]
I use Snappy-sql to query data, unable to do any operations, lack of memory, error message as follows, my host memory is still a space
```
snappy> show tables in app;
错误 XCL54：(SQLState=XCL54 Severity=30000) (Server=cloudera1/192.168.15.122[1527] Thread=pool-3-thread-26) XCL54.T : [0] EXECUTE STATEMENT SYS."getTables", [1] cloudera1(101203)<v1>:23457
snappy> 
```
```
[root@cloudera2 ~]# free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        1.2G         11G         24M        2.6G         14G
Swap:          7.9G          0B        7.9G
```

**Comment by sumwale** [comment]
@diwenjing Can you post the server memory usage details as seen in dashboard?

**Comment by sumwale** [comment]
@diwenjing Did you get to see server memory-usage etc in dashboard and did anything seem out of place. You need at least 4GB RAM to work, and usually more depending on data size unless you intend to use SnappyData as an on-disk store rather than a memory-optimized one. Also see last comments here https://github.com/SnappyDataInc/snappydata/issues/698 and https://github.com/SnappyDataInc/snappydata/issues/686#issuecomment-313405908 for more explanation.
