### ISSUE TITLE
Tables created on HDFS STORE to be accessed from outside snappydata

### ISSUE THREAD

**Issue by asishbose** [SnappyDataInc/snappydata#877]
There is nothing mentioned in snappydata documentation about HDFSSTORE but on gemfire it is mentioned.
On the contrary I am able to create HDFSSTORE in snappydata. 
Consider I create a table in HDFSSTORE. Will I be able to view this file as an external table to be accessible via hive or spark [apache-spark and not the one with snappy] -using hive-site.xml ?

**Comment by sumwale** [comment]
@asishbose Support for HDFSSTORE has been removed in SnappyData (though old GemFire code still supports but will be removed soon) due to its various limitations. Currently supported way to backup data to HDFS is to use the normal Spark DataFrameWriter API e.g. `session.table("table1").write.parquet("hdfs://...")`. This has multiple advantages including a consistent and current snapshot of data, standard Parquet/ORC and other formats supported by Spark among others.

In future we are considering adding Parquet as a native storage format too so that one can just copy the files as required.

Closing this issue -- please open another if there is any trouble in using the standard Spark APIs.
